### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by cl-ement05** [flybywiresim/simbridge#101]
```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: UNKNOWN: unknown error, open 'C:\Users\cleme\AppData\Local\Temp\pkg-BIBPqB\46733a37a0a969c718b268a1e2c2d0b911228180a869e0241444baad0fff0484'
    at Object.openSync (node:fs:599:3)
    at Object.openSync (pkg/prelude/bootstrap.js:793:32)
    at uncompressExternallyAndOpen (pkg/prelude/bootstrap.js:748:19)
    at openFromSnapshot (pkg/prelude/bootstrap.js:771:30)
    at Object.openSync (pkg/prelude/bootstrap.js:798:12)
    at copyInChunks (pkg/prelude/bootstrap.js:169:26)
    at Object.copyFileSync (pkg/prelude/bootstrap.js:1182:5)
    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:247:12)
    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:203:9)
    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:203:9) {
  errno: -4094,
  syscall: 'open',
  code: 'UNKNOWN',
  path: 'C:\\Users\\cleme\\AppData\\Local\\Temp\\pkg-BIBPqB\\46733a37a0a969c718b268a1e2c2d0b911228180a869e0241444baad0fff0484'
}

Node.js v18.5.0
```
I have SimBridge, A32NX and FS2020 latest versions

**Comment by Maximilian-Reuter** [comment]
People have had success resolving this issue by installing the Microsoft Visual C++ Redistributables
https://aka.ms/vs/17/release/vc_redist.x64.exe
This is a link to the most current one. Try and see if that resolves your issue

**Comment by cl-ement05** [comment]
Worked perfectly thank you !
