### ISSUE TITLE
SimBridge does not start

### ISSUE THREAD

**Issue by tkohlmeier** [flybywiresim/simbridge#106]
I have installed version 0.5.2 using the FBW installer. When trying to start SimBridge from the installer, a console window opens and closes almost immediately. When starting `fbw-simbridge.exe` from a console I get this output:

```
[FBW-SimBridge] info    2023-12-3 11:16:58 [NestFactory] Starting Nest application... +3ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] AppModule dependencies initialized +1ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] HttpModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] TerminusModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] TerrainModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] ServeStaticModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] ConfigModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] InterfacesModule dependencies initialized +1ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] CoRouteModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] HealthModule dependencies initialized +1ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] WinstonModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [InstanceLoader] UtilitiesModule dependencies initialized +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [McduGateway] Remote MCDU websocket initialised +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RoutesResolver] CoRouteController {/api/v1/coroute}: +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/coroute/length, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/coroute, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/coroute/list, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RoutesResolver] UtilityController {/api/v1/utility}: +1ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/utility/pdf, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/utility/pdf/list, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/utility/pdf/listdir, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/utility/pdf/numpages, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/utility/image, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/utility/image/list, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RoutesResolver] TerrainController {/api/v1/terrain}: +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/terrain/renderingTimestamp, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/terrain/renderingThresholds, GET} route +0ms[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/terrain/renderingFrames, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/api/v1/terrain/verticalDisplayPath, POST} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RoutesResolver] HealthController {/health}: +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/health, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [RouterExplorer] Mapped {/health/kill, GET} route +0ms
[FBW-SimBridge] info    2023-12-3 11:16:58 [NestApplication] Nest application successfully started +0ms
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:692:9)
    at Object.spawn (pkg/prelude/bootstrap.js:2076:27)
    at SysTray.<anonymous> (C:\snapshot\simbridge\node_modules\systray2\index.js:292:63)
    at step (C:\snapshot\simbridge\node_modules\systray2\index.js:52:23)
    at Object.next (C:\snapshot\simbridge\node_modules\systray2\index.js:33:53)
    at C:\snapshot\simbridge\node_modules\systray2\index.js:27:71
    at new Promise (<anonymous>)
    at C:\snapshot\simbridge\node_modules\systray2\index.js:23:12
    at C:\snapshot\simbridge\node_modules\systray2\index.js:285:99 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v18.5.0
Windows PowerShell[13924]: C:\Users\runneradmin\AppData\Local\Temp\pkg.24e0b2b2d51e47b9dba34c30\node\src\node_zlib.cc:281: Assertion `init_done_ && "close before init"' failed.
 1: 00007FF6FC2F43DF node_api_throw_syntax_error+177759
 2: 00007FF6FC282316 v8::base::CPU::num_virtual_address_bits+67334
 3: 00007FF6FC2826E2 v8::base::CPU::num_virtual_address_bits+68306
 4: 00007FF6FC1A7887 cppgc::internal::PageMemoryRegion::reserved_region+40343
 5: 00007FF6FC1A67CC cppgc::internal::PageMemoryRegion::reserved_region+36060
 6: 00007FF6FC1A6AD4 cppgc::internal::PageMemoryRegion::reserved_region+36836
 7: 00007FF6FC2F296C node_api_throw_syntax_error+170988
 8: 00007FF6FC31E070 node::FreeEnvironment+112
 9: 00007FF6FC1B7975 v8::internal::wasm::SignatureMap::Freeze+34213
10: 00007FF6FC1B35B8 v8::internal::wasm::SignatureMap::Freeze+16872
11: 00007FF6FC34223D uv_poll_stop+557
12: 00007FF6FD2FCA7A v8::internal::compiler::ToString+138378
13: 00007FFED6C27344 BaseThreadInitThunk+20
14: 00007FFED83626B1 RtlUserThreadStart+33
```

I also tried to start SimBridge using `npm run start`. After copying `properties.json` and the terrain folder to my repository (why is this not described in the readme?), it works.

How can I fix this problem? And why is the error not logged to the log file?

**Comment by DieterKuep** [comment]
This is Dieter from germany , i have the same problem.
is it posible for you to describe which files (from which folder) i had to copy?
the directory from the resources folder is located in the community folder/flybywire externaltools simbridge.
So many thanks for any help
greetings
Dieter

**Comment by tkohlmeier** [comment]
I copied the properties.json file from the resources folder you mentioned to the resources folder in the repository root + the terrain folder from the flybywire-externaltools-simbridge folder to the repository root. I hope this helps.

**Comment by tkohlmeier** [comment]
I just tried running SimBridge from the installer using the current version (0.6.2) and it works now. It is normal that the console window is visible for a very short time only - a tray icon should appear from where you can show or hide the console window. So I'm closing this issue as it seems to be fixed.

**Comment by DieterKuep** [comment]
OK thanks so lot
my simbridge also is working now!!
greetingsDieter    Am Samstag, 16. November 2024 um 14:22:19 MEZ hat tkohlmeier ***@***.***> Folgendes geschrieben:   

 


I just tried running SimBridge from the installer using the current version (0.6.2) and it works now. It is normal that the console window is visible for a very short time only - a tray icon should appear from where you can show or hide the console window. So I'm closing this issue as it seems to be fixed.

**Comment by Dmedibas** [comment]
I have similar issue, I have tried all you can imagine, even fresh win10 load, clean from scratch, same thing, if I execute in terminal window it stops with error. Is there anything else I could miss, .NET Java etc? I can't understand why it's not working.
Many thanks
