### ISSUE TITLE
SimBridge cannot start missing module

### ISSUE THREAD

**Issue by user7228** [flybywiresim/simbridge#69]
Trying to start Simbridge from the FBW installer, a black screen appear momentarily and disappeared. Then trying from cmd and got these:

```
C:\Users\user\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-externaltools-simbridge>fbw-simbridge.exe
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\user\AppData\Local\Temp\pkg\f5be2927aa84e70439593a65cd846335970cabe0c6914a148cd082b4003329d0\skia-canvas\lib\v6\index.node
    at process.dlopen (pkg/prelude/bootstrap.js:2255:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\simbridge\node_modules\skia-canvas\lib\index.js:23:29)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by Lucky38i** [comment]
Is this still occuring on the latest version?

**Comment by Lucky38i** [comment]
Closing this as stale.
